[workspace]
resolver = "2"
members = [
    "guideline-core",
    "guideline-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/guide-inc-org/guideline"

[workspace.dependencies]
nom = "8"
thiserror = "2"
wasm-bindgen = "0.2"
